In [2]:
import pandas as pd
#To turn off warning messages
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Steps we need to perform!
# Getting the data from the site.
#Reading all 5 pages of the data
#Figure out which classes are grad anbd which are undergrad
#Display the undergrad 8am and undergrad Friday classes

In [31]:
def get_ischool_classes():
    classes = pd.DataFrame() 

    for i in range(1,6):
        link = 'https://ischool.syr.edu/classes/?page=' + str(i)
        data = pd.read_html(link)    
        classes = classes.append(data[0], ignore_index=True)
    
    classes.columns = ['Course','Section','ClassNo','Credits','Title','Instructor','Time','Days','Room']

    return classes

In [33]:
classes = get_ischool_classes()
classes.sample(5)

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room
235,IST971,M800,41561,1.0,Internship in Info Studies,Susan Monica Bonzi,12:00am - 12:00am,NaN,NaN
19,IST195,M008,37667,3.0,LAB: Information Technologies,Jeff Rubin,2:55pm - 3:50pm,F,Hinds Hall 010
210,IST719,M402,43381,3.0,Information Visualization,Gary E Krudys,12:00am - 8:30pm,Tu,Online Online
44,IST335,M001,37620,3.0,Intro/Info Based Organizations,Jeffrey Fouts,2:00pm - 3:20pm,TuTh,Hinds Hall 011
48,IST337,M001,37848,1.0,IM&T Support Practicum,Jeffrey Fouts,2:15pm - 5:00pm,F,Hinds Hall 117

In [34]:
#So now we have our data! Now proceeding to step 2 and figuring out which courses are undergrad! 
#As a matter of fact the courses with last three numbers >= 500 are Grad courses and those < 500 are Ugrad

In [38]:
classes['Number'] = classes['Course'].str[3:] 
classes['Type'] = ''
classes['Type'][classes['Number'] >= '500'] = 'Grad' 
classes['Type'][classes['Number'] < '500'] = 'UGrad'

In [54]:
#Observe that we have a Type column now
classes.tail()

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Number,Type
239,IST972,M401,37927,3.0,School Media Practicum,Patricia C Vilello,12:00am - 12:00am,NaN,Online,972,Grad
240,IST973,M800,37882,1.0,Internship in Info Studies,Rebecca Shaffer Mannion,12:00am - 12:00am,NaN,NaN,973,Grad
241,IST973,M401,37920,1.0,Internship in Info Studies,Rebecca Shaffer Mannion,12:00am - 12:00am,NaN,Online,973,Grad
242,IST990,M001,43689,1.0,Independent Study,NaN,12:00am - 12:00am,NaN,NaN,990,Grad
243,IST999,M001,37610,1.0,Dissertation,NaN,12:00am - 12:00am,NaN,NaN,999,Grad

In [58]:
Friday = classes[ (classes['Type'] == 'UGrad') & (classes['Days'].str.find('F')>=0 ) ]
Friday

,Course,Section,ClassNo,Credits,Title,Instructor,Time,Days,Room,Number,Type
6,IDS403,M001,37649,1.0,Startup Sandbox,John DuRoss Liddy,2:15pm - 5:05pm,F,Syracuse Technology Garden,403,UGrad
7,IDS460,M002,37755,3.0,Entretech - NYC,John DuRoss Liddy,12:00am - 12:00am,MTuWThF,Courtyard Marriott Man Midtwn Online Online,460,UGrad
8,IDS460,M003,37756,3.0,Spring Break in Silicon Valley,John DuRoss Liddy,12:00am - 12:00am,MTuWThFSu,"Online Online Residence Inn by Marr, San Mat",460,UGrad
14,IST195,M003,37658,3.0,LAB: Information Technologies,Jeff Rubin,9:30am - 10:25am,F,Hinds Hall 010,195,UGrad
15,IST195,M004,37659,3.0,LAB: Information Technologies,Jeff Rubin,10:35am - 11:30am,F,Hinds Hall 010,195,UGrad
16,IST195,M005,37660,3.0,LAB: Information Technologies,Jeff Rubin,11:40am - 12:35pm,F,Hinds Hall 010,195,UGrad
17,IST195,M006,37661,3.0,LAB: Information Technologies,Jeff Rubin,12:45pm - 1:40pm,F,Hinds Hall 010,195,UGrad
18,IST195,M007,37662,3.0,LAB: Information Technologies,Jeff Rubin,1:50pm - 2:45pm,F,Hinds Hall 010,195,UGrad
19,IST195,M008,37667,3.0,LAB: Information Technologies,Jeff Rubin,2:55pm - 3:50pm,F,Hinds Hall 010,195,UGrad
20,IST195,M002,37695,3.0,LAB: Information Technologies,Jeff Rubin,8:25am - 9:20am,F,Hinds Hall 010,195,UGrad
21,IST195,M009,41659,3.0,LAB: Information Technologies,Lauren J Hardee-Chase,10:35am - 11:30am,F,Hinds Hall 013,195,UGrad
22,IST195,M010,41832,3.0,LAB: Information Technologies,Lauren J Hardee-Chase,11:40am - 12:35pm,F,Hinds Hall 013,195,UGrad
25,IST233,M003,37663,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,10:35am - 11:30am,F,Hinds Hall 027,233,UGrad
26,IST233,M004,37664,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,11:40am - 12:35pm,F,Hinds Hall 027,233,UGrad
27,IST233,M005,37665,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,12:45pm - 1:40pm,F,Hinds Hall 027,233,UGrad
28,IST233,M006,37666,3.0,LAB: Intro to Computer Networking,S Bruce Boardman,1:50pm - 2:45pm,F,Hinds Hall 027,233,UGrad
48,IST337,M001,37848,1.0,IM&T Support Practicum,Jeffrey Fouts,2:15pm - 5:00pm,F,Hinds Hall 117,337,UGrad
99,IST486,M002,42625,3.0,Social Media in the Organiz.,Kristy Lee Hochenberger,9:30am - 10:25am,MWF,Hinds Hall 021,486,UGrad

In [63]:
Ugrad = classes[classes['Type'] == 'UGrad']
Eight_am = classes[ (classes['Type'] == 'UGrad') & (classes['Time'].str.startswith('8:00am') ) ]

98